# Generated by Django 5.1.4 on 2025-01-14 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchword',
            name='admin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='search_words', to='administration.admin', verbose_name='Администратор'),
            preserve_default=False,
        ),
    ]
