# Generated by Django 5.1.4 on 2025-01-14 13:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_searchword_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='searchword',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.admin', verbose_name='Админ'),
        ),
    ]
