# Generated by Django 5.1.4 on 2025-01-17 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="url",
            field=models.CharField(
                unique=True,
                verbose_name="Ссылка на Telegram-канал",
            ),
        ),
    ]
