# Generated by Django 5.1.5 on 2025-01-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0002_alter_channel_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="last_parsed_at",
        ),
        migrations.RemoveField(
            model_name="post",
            name="next_parse_at",
        ),
        migrations.AddField(
            model_name="channel",
            name="next_parse_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                null=True,
                verbose_name="Время начала следующего парсинга",
            ),
        ),
    ]
