# Generated by Django 5.1.5 on 2025-02-07 08:25

import channels.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "channels",
            "0003_remove_post_last_parsed_at_remove_post_next_parse_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="channel",
            options={"verbose_name": "Канал", "verbose_name_plural": "Каналы"},
        ),
        migrations.AlterField(
            model_name="channel",
            name="url",
            field=models.CharField(
                help_text="Формат ссылки: https://t.me/s/<username>",
                unique=True,
                validators=[channels.models.channel_url_validator],
                verbose_name="Ссылка на Telegram-канал",
            ),
        ),
    ]
