# Generated by Django 5.1.4 on 2025-01-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0005_alter_post_options_alter_post_channel_alter_post_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='channel',
            name='last_scanned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее сканирование'),
        ),
        migrations.AddField(
            model_name='channel',
            name='next_scan_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Следующее сканирование'),
        ),
        migrations.AddField(
            model_name='channel',
            name='scan_interval',
            field=models.PositiveIntegerField(default=2, verbose_name='Интервал сканирования (минуты)'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
