# Generated by Django 5.1.4 on 2025-01-14 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0006_rename_active_channel_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='interval_minutes',
            field=models.PositiveIntegerField(default=2, verbose_name='Интервал парсинга в минутах'),
        ),
        migrations.AddField(
            model_name='channel',
            name='priority',
            field=models.IntegerField(default=1, verbose_name='Приоритет парсинга'),
        ),
    ]
