# Generated by Django 5.1.4 on 2025-01-15 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0007_channel_interval_minutes_channel_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='ID поста'),
        ),
    ]
