# Generated by Django 5.1.4 on 2025-01-15 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0009_alter_post_options_alter_post_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='channel_name',
            new_name='name',
        ),
    ]
