# Generated by Django 5.1.4 on 2025-01-15 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0010_rename_channel_name_channel_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='telegram_link',
            new_name='url',
        ),
    ]
