# Generated by Django 5.1.4 on 2025-01-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0011_rename_telegram_link_channel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст поста'),
        ),
    ]
