# Generated by Django 5.1.4 on 2025-01-15 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0012_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='last_scanned_at',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='next_scan_at',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='channel',
            name='scan_interval',
        ),
        migrations.AlterField(
            model_name='channel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='interval_minutes',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Интервал парсинга в минутах'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
