# Generated by Django 5.1.4 on 2025-01-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0014_alter_post_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_parsed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время последнего парсинга'),
        ),
        migrations.AddField(
            model_name='post',
            name='next_parse_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала следующего парсинга'),
        ),
    ]
