# Generated by Django 5.1.4 on 2025-01-16 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0015_post_last_parsed_at_post_next_parse_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('post_id', 'channel')},
        ),
    ]
