# Generated by Django 5.1.4 on 2025-01-16 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0017_alter_post_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_parsed_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время последнего парсинга'),
        ),
        migrations.AlterField(
            model_name='post',
            name='next_parse_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True, verbose_name='Время начала следующего парсинга'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.PositiveIntegerField(verbose_name='ID поста'),
        ),
    ]
