# Generated by Django 5.1.4 on 2025-01-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('level', models.CharField(max_length=50, verbose_name='Уровень')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('additional_data', models.JSONField(blank=True, null=True, verbose_name='Дополнительные данные')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True, verbose_name='Ключ')),
                ('value', models.JSONField(verbose_name='Значение')),
            ],
        ),
    ]
