# Generated by Django 5.1.4 on 2025-01-17 06:49

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(2)],
                        verbose_name="Ключевое слово",
                    ),
                ),
                (
                    "lemma",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Лемма слова",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ключевое слово",
                "verbose_name_plural": "Ключевые слова",
            },
        ),
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "telegram_id",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        verbose_name="Telegram ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Имя администратора",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Дата создания",
                    ),
                ),
                (
                    "channels",
                    models.ManyToManyField(
                        blank=True,
                        related_name="admins",
                        to="channels.channel",
                        verbose_name="Каналы, на которые подписан администратор",
                    ),
                ),
                (
                    "words",
                    models.ManyToManyField(
                        blank=True,
                        related_name="admins",
                        to="users.searchword",
                        verbose_name="Ключевые слова, доступные админу",
                    ),
                ),
            ],
        ),
    ]
