# Generated by Django 5.1.5 on 2025-02-07 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admin",
            options={
                "verbose_name": "Администратор",
                "verbose_name_plural": "Администраторы",
            },
        ),
        migrations.AddField(
            model_name="admin",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admins",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="admin",
            name="telegram_id",
            field=models.CharField(
                help_text="ID пользователя в Telegram. Например, 80567890, можно узнать у @userinfobot",
                max_length=255,
                unique=True,
                verbose_name="Telegram ID",
            ),
        ),
    ]
