# Generated by Django 5.1.4 on 2025-01-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='searchword',
            unique_together={('word', 'lemma')},
        ),
        migrations.AddField(
            model_name='searchword',
            name='admins',
            field=models.ManyToManyField(related_name='search_words', to='users.admin', verbose_name='Администраторы'),
        ),
        migrations.AlterField(
            model_name='searchword',
            name='word',
            field=models.CharField(max_length=255, verbose_name='Ключевое слово'),
        ),
        migrations.RemoveField(
            model_name='searchword',
            name='admin',
        ),
    ]
