# Generated by Django 5.1.4 on 2025-01-15 12:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_searchword_unique_together_searchword_admins_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchword',
            options={'verbose_name': 'Ключевое слово', 'verbose_name_plural': 'Ключевые слова'},
        ),
        migrations.AlterUniqueTogether(
            name='searchword',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя администратора'),
        ),
        migrations.AlterField(
            model_name='searchword',
            name='word',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Ключевое слово'),
        ),
    ]
