# Generated by Django 5.1.5 on 2025-02-07 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_admin_options_admin_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="telegram_id",
            field=models.CharField(
                help_text='ID пользователя в Telegram. Например, 80567890, можно узнать у @userinfobot, группы чатов начинаются с знака "-" (минус).',
                max_length=255,
                unique=True,
                verbose_name="Telegram ID",
            ),
        ),
        migrations.AlterField(
            model_name="admin",
            name="user",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admins",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
