# Generated by Django 5.1.4 on 2025-01-16 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_searchword_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchword',
            name='admins',
        ),
        migrations.AddField(
            model_name='admin',
            name='words',
            field=models.ManyToManyField(blank=True, related_name='admins', to='users.searchword', verbose_name='Ключевые слова, доступные админу'),
        ),
    ]
