# Generated by Django 5.1.4 on 2025-01-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0016_alter_post_unique_together'),
        ('users', '0004_remove_searchword_admins_admin_words'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='channels',
            field=models.ManyToManyField(blank=True, related_name='admins', to='channels.channel', verbose_name='Каналы, на которые подписан администратор'),
        ),
    ]
